### ISSUE TITLE
Add support for custom config file

### ISSUE THREAD

**Issue by roelofr** [HCESrl/gitlab-standard-labels#1]
The list is pretty standard, but not all labels are suitable for all users. Which is why I propse an option to pick a custom config file.

Maybe a `--config=` or `-c` option to point to a custom JSON file, that you validate using a JSON schema.

Based on the current [labels/config.json](https://github.com/HCESrl/gitlab-standard-labels/blob/master/labels/config.json), I made the following schema:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "https://github.com/hcesrl/gitlab-standard-labels/schema/labels.json#",
    "$comment": "Defines a list of labels to use",
    "title": "Label definition file",
    "description": "Contains a list of an unrestricted number of labels",
    "type": "array",
    "minItems": 1,
    "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
            "name",
            "color"
        ],
        "properties": {
            "name": {
                "type": "string",
                "minLength": 1,
                "maxLength": 64
            },
            "color": {
                "type": "string",
                "regex": "^#[0-9a-f]{6}$"
            },
            "priority": {
                "type": "number",
                "enum": [
                    1
                ]
            },
            "board": {
                "type": "boolean",
                "enum": [
                    true
                ]
            }
        }
    }
}
```

The schema also points out some irregularities, such as the use of `priority` but only using a value of `1` and the `board` flag only allowing `true`, which seems like it should be either `true` or `false`.

Let me know what you think :wink:

**Comment by fsavina** [comment]
Hi @roelofr, it make perfectly sense. We'll take a deeper look at it and let you know, thanks!

**Comment by fsavina** [comment]
@roelofr we've added the custom config feature to the new release `v0.1.0`. Thanks for the suggestion!

**Comment by roelofr** [comment]
Wow, talking about quick work.

Nice work :+1:
